import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Providers } from '@/providers';
import { cn } from '@/lib/utils';
import './globals.css';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-montserrat antialiased', montserrat.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
