export const TOKEN = {
  VERIFICATION_EMAIL_COOLDOWN_MINUTES: 3,
  PASSWORD_RESET_COOLDOWN_MINUTES: 3,
  VERIFICATION_TOKEN_LENGTH: 64,
  DEFAULT_TOKEN_LENGTH: 32,
  EMAIL_VERIFICATION_EXPIRY_MINUTES: 24 * 60, // 24 hours
  PASSWORD_RESET_EXPIRY_MINUTES: 30,
} as const;

export const REFRESH_TOKEN_COOKIE = 'refreshToken';