export const APP_CONSTANTS = {
  // Application
  APP_NAME: 'MyApp',
  APP_VERSION: '1.0.0',
  APP_DESCRIPTION: 'This is my application',

  // Pagination
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,

  // Password
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  PASSWORD_SALT_ROUNDS: 12,

  // Tokens
  VERIFICATION_EMAIL_COOLDOWN_MINUTES: 3,
  VERIFICATION_TOKEN_LENGTH: 64,
  DEFAULT_TOKEN_LENGTH: 32,
  EMAIL_VERIFICATION_EXPIRY_MINUTES: 24 * 60, // 24 hours
  PASSWORD_RESET_EXPIRY_MINUTES: 30,
};
